# Generated by Django 5.2.9 on 2025-12-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=30)),
                ('imagenet_class', models.TextField(max_length=30)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
